spring:
  application:
    name: flight-search-api
  datasource:
    url: jdbc:postgresql://localhost:5432/airport_test
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop



api:
  flight:
    url: https://api.amadeus.com/test/new-flights
server:
  port: 3535

secret:
  key: zCoSeBvkWpWq2ZGAXDhE+AYp38blL07EZIoMFYwd1VCFNh2VJ8PbB4jaP1fAYPBRvmLXoZ7+HMTRAJ2NPvTehw==
